imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        storage_id: session.storage.pdo

parameters:
    pdo.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

services:
    vdvreede.twig.extension.call:
      class: Vdvreede\TFrontendBundle\Twig\Extensions
      tags:
        - { name: twig.extension }
    
    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo, %session.storage.options%, %pdo.db_options%]

    pdo:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=t_session_dev"
            user:     root
            password: null

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'form_table_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        charset:  UTF8
        default_connection: main

    orm: 
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
          default:
            connection: main            
            mappings:
              VdvreedeTFrontendBundle: ~
          audit:
            connection: audit
            mappings:
              StofDoctrineExtensionsBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
# settings for the doctrine extras including timestampable
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        audit:
          tree: false
          sluggable: false
          translatable: false
          loggable: true
          timestampable: false
        main:
          tree: false
          sluggable: false
          translatable: false
          loggable: false
          timestampable: true
          
