security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Vdvreede\TFrontendBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main:
        entity: { class: Vdvreede\TFrontendBundle\Entity\User, property: email }            
        
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        secured_area:
          pattern: ^/
          http_basic:
            realm: "Test security"           

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
