import_file:
  pattern: /import/{accountId}
  defaults: { _controller: VdvreedeTFrontendBundle:Import:file }
  requirements:
    accountId: \d+

import_process:
  pattern: /import/{accountId}/process/{transImportId}
  defaults: { _controller: VdvreedeTFrontendBundle:Import:process, transImportId: 0 }
  requirements:
    accountId: \d+
    transImportId: \d+
    _method: POST
    
transactions:
  resource: "@VdvreedeTFrontendBundle/Controller/TransactionController.php"
  type: annotation
  
accounts:
  resource: "@VdvreedeTFrontendBundle/Controller/AccountController.php"
  type: annotation
  
categories:
  resource: "@VdvreedeTFrontendBundle/Controller/CategoryController.php"
  type: annotation
  