
category_new:
  pattern: /category/new
  defaults: { _controller: VdvreedeTFrontendBundle:Category:new }
  
category_edit:
  pattern: /category/edit/{categoryId}
  defaults: { _controller: VdvreedeTFrontendBundle:Category:edit }
  
category_list:
  pattern: /category
  defaults: { _controller: VdvreedeTFrontendBundle:Category:index }

import_file:
  pattern: /import/{accountId}
  defaults: { _controller: VdvreedeTFrontendBundle:Import:file }
  requirements:
    accountId: \d+

import_process:
  pattern: /import/{accountId}/process
  defaults: { _controller: VdvreedeTFrontendBundle:Import:process }
  requirements:
    accountId: \d+
    _method: POST
    
transactions:
  resource: "@VdvreedeTFrontendBundle/Controller/TransactionController.php"
  type: annotation
  
accounts:
  resource: "@VdvreedeTFrontendBundle/Controller/AccountController.php"
  type: annotation
  