account_new:
  pattern: /account/new
  defaults: { _controller: VdvreedeTFrontendBundle:Account:new }
  
account_edit:
  pattern: /account/edit/{accountId}
  defaults: { _controller: VdvreedeTFrontendBundle:Account:edit }
  
account_list:
  pattern: /account
  defaults: { _controller: VdvreedeTFrontendBundle:Account:index }